In [1]:
import pandas as pd
from chembl_webresource_client.new_client import new_client as searcher

# Search For the Target

In [2]:
target_search = searcher.target.search('Aromatase')
searched_df = pd.DataFrame.from_dict(target_search)
searched_df

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,"[{'xref_id': 'P11511', 'xref_name': None, 'xre...",Homo sapiens,Cytochrome P450 19A1,20.0,False,CHEMBL1978,"[{'accession': 'P11511', 'component_descriptio...",SINGLE PROTEIN,9606
1,"[{'xref_id': 'P22443', 'xref_name': None, 'xre...",Rattus norvegicus,Cytochrome P450 19A1,20.0,False,CHEMBL3859,"[{'accession': 'P22443', 'component_descriptio...",SINGLE PROTEIN,10116

### Select the target
In this case the first one with index [0]

In [3]:
selected_target = searched_df['target_chembl_id'][0]
selected_target

'CHEMBL1978'

## Now download activity data of the selected target from ChEMBL server

In [4]:
downloader = searcher.activity.filter(target_chembl_id = selected_target).filter(standard_type = 'IC50') #Get IC50 only
data = pd.DataFrame.from_dict(downloader)
data

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,82585,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,7.1
1,None,None,94540,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,50.0
2,None,None,112960,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.238
3,None,None,116766,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.057
4,None,None,118017,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24742461,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5118295,Inhibition of aromatase in human JEG-3 cells u...,B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,nM,UO_0000065,None,50.1
2962,None,None,24783443,[],CHEMBL5130158,Inhibition of human placental microsome CYP19 ...,A,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,10.0
2963,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24886565,[],CHEMBL5157477,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.031
2964,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24886566,[],CHEMBL5157477,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.042
2965,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24886567,[],CHEMBL5157477,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.026000000000000002

In [5]:
!mkdir -p 'datasets'

In [7]:
# save the raw data for further processing
data.to_csv('datasets/raw_data.csv', index = False)

In [11]:
#show available columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 46 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   action_type                85 non-null     object
 1   activity_comment           94 non-null     object
 2   activity_id                2966 non-null   int64
 3   activity_properties        2966 non-null   object
 4   assay_chembl_id            2966 non-null   object
 5   assay_description          2966 non-null   object
 6   assay_type                 2966 non-null   object
 7   assay_variant_accession    0 non-null      object
 8   assay_variant_mutation     0 non-null      object
 9   bao_endpoint               2966 non-null   object
 10  bao_format                 2966 non-null   object
 11  bao_label                  2966 non-null   object
 12  canonical_smiles           2966 non-null   object
 13  data_validity_comment      127 non-null    object
 14  data_validity_description  127 non-null    object
 15  document_chembl_id         2966 non-null   object
 16  document_journal           2941 non-null   object
 17  document_year              2966 non-null   int64
 18  ligand_efficiency          2484 non-null   object
 19  molecule_chembl_id         2966 non-null   object
 20  molecule_pref_name         340 non-null    object
 21  parent_molecule_chembl_id  2966 non-null   object
 22  pchembl_value              2521 non-null   object
 23  potential_duplicate        2966 non-null   int64
 24  qudt_units                 2919 non-null   object
 25  record_id                  2966 non-null   int64
 26  relation                   2890 non-null   object
 27  src_id                     2966 non-null   int64
 28  standard_flag              2966 non-null   int64
 29  standard_relation          2890 non-null   object
 30  standard_text_value        0 non-null      object
 31  standard_type              2966 non-null   object
 32  standard_units             2920 non-null   object
 33  standard_upper_value       0 non-null      object
 34  standard_value             2890 non-null   object
 35  target_chembl_id           2966 non-null   object
 36  target_organism            2966 non-null   object
 37  target_pref_name           2966 non-null   object
 38  target_tax_id              2966 non-null   object
 39  text_value                 0 non-null      object
 40  toid                       0 non-null      object
 41  type                       2966 non-null   object
 42  units                      2735 non-null   object
 43  uo_units                   2920 non-null   object
 44  upper_value                0 non-null      object
 45  value                      2890 non-null   object
dtypes: int64(6), object(40)
memory usage: 1.0+ MB

In [9]:
data.describe()

,activity_id,document_year,potential_duplicate,record_id,src_id,standard_flag
count,2.966000e+03,2966.000000,2966.000000,2.966000e+03,2966.000000,2966.000000
mean,7.259820e+06,2007.971342,0.129467,1.321475e+06,1.305799,0.974039
std,7.107547e+06,8.198436,0.335773,1.056590e+06,3.317572,0.159045
min,8.258500e+04,1986.000000,0.000000,4.054000e+03,1.000000,0.000000
25%,1.675999e+06,2005.000000,0.000000,4.227722e+05,1.000000,1.000000
50%,3.302044e+06,2010.000000,0.000000,9.135265e+05,1.000000,1.000000
75%,1.497024e+07,2014.000000,0.000000,2.245836e+06,1.000000,1.000000
max,2.488657e+07,2022.000000,1.000000,3.889407e+06,38.000000,1.000000

In [10]:
data['standard_type'].unique()

array(['IC50'], dtype=object)

In [12]:
data['standard_units'].value_counts()

nM         2890
ug.mL-1      29
mg kg-1       1
Name: standard_units, dtype: int64