# Preprocessing of the Raw downloaded data

In [1]:
import pandas as pd

In [2]:
raw_data = pd.read_csv('datasets/raw_data.csv')
raw_data

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,NaN,NaN,82585,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,7.100
1,NaN,NaN,94540,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,50.000
2,NaN,NaN,112960,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,0.238
3,NaN,NaN,116766,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,0.057
4,NaN,NaN,118017,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,0.054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,24742461,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5118295,Inhibition of aromatase in human JEG-3 cells u...,B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,50.100
2962,NaN,NaN,24783443,[],CHEMBL5130158,Inhibition of human placental microsome CYP19 ...,A,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,10.000
2963,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,24886565,[],CHEMBL5157477,Inhibition of aromatase (unknown origin),B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,0.031
2964,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,24886566,[],CHEMBL5157477,Inhibition of aromatase (unknown origin),B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,0.042
2965,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,24886567,[],CHEMBL5157477,Inhibition of aromatase (unknown origin),B,NaN,NaN,BAO_0000190,...,Homo sapiens,Cytochrome P450 19A1,9606,NaN,NaN,IC50,uM,UO_0000065,NaN,0.026

In [3]:
# getting the column names of the dataframe
# data.info()
list(raw_data.columns)

['action_type',
 'activity_comment',
 'activity_id',
 'activity_properties',
 'assay_chembl_id',
 'assay_description',
 'assay_type',
 'assay_variant_accession',
 'assay_variant_mutation',
 'bao_endpoint',
 'bao_format',
 'bao_label',
 'canonical_smiles',
 'data_validity_comment',
 'data_validity_description',
 'document_chembl_id',
 'document_journal',
 'document_year',
 'ligand_efficiency',
 'molecule_chembl_id',
 'molecule_pref_name',
 'parent_molecule_chembl_id',
 'pchembl_value',
 'potential_duplicate',
 'qudt_units',
 'record_id',
 'relation',
 'src_id',
 'standard_flag',
 'standard_relation',
 'standard_text_value',
 'standard_type',
 'standard_units',
 'standard_upper_value',
 'standard_value',
 'target_chembl_id',
 'target_organism',
 'target_pref_name',
 'target_tax_id',
 'text_value',
 'toid',
 'type',
 'units',
 'uo_units',
 'upper_value',
 'value']

In [4]:
# select only required columns

data = raw_data[['canonical_smiles', 'molecule_chembl_id', 'standard_value']]
data

,canonical_smiles,molecule_chembl_id,standard_value
0,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12,CHEMBL341591,7100.0
1,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,CHEMBL2111947,50000.0
2,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21,CHEMBL431859,238.0
3,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21,CHEMBL113637,57.0
4,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21,CHEMBL112021,54.0
...,...,...,...
2961,C=C1C[C@@H]2[C@H](CC[C@]3(C)C(=O)CC[C@@H]23)[C...,CHEMBL1200374,50.1
2962,O=C(Nc1ccc2[nH]ncc2c1)[C@]12ON=C(c3cccnc3)[C@H...,CHEMBL5184829,10000.0
2963,CCOC(=O)Cc1csc(N/N=C/c2ccc3cc(OC)ccc3c2)n1,CHEMBL5176279,31.0
2964,COc1ccc2cc(/C=N/NC3=NC(=O)CS3)ccc2c1,CHEMBL5177928,42.0
2965,N#Cc1ccc(C(c2ccc(C#N)cc2)n2cncn2)cc1,CHEMBL1444,26.0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   canonical_smiles    2966 non-null   object
 1   molecule_chembl_id  2966 non-null   object
 2   standard_value      2890 non-null   float64
dtypes: float64(1), object(2)
memory usage: 69.6+ KB

In [6]:
data['standard_value'].describe()

count    2.890000e+03
mean     2.173576e+10
std      7.235369e+11
min      0.000000e+00
25%      1.000000e+02
50%      1.000000e+03
75%      7.370000e+03
max      3.388442e+13
Name: standard_value, dtype: float64

## Handling Missing Values

In [7]:
handled_standard_value = data[data['standard_value'].notna()]
handled_standard_value

,canonical_smiles,molecule_chembl_id,standard_value
0,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12,CHEMBL341591,7100.0
1,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,CHEMBL2111947,50000.0
2,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21,CHEMBL431859,238.0
3,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21,CHEMBL113637,57.0
4,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21,CHEMBL112021,54.0
...,...,...,...
2961,C=C1C[C@@H]2[C@H](CC[C@]3(C)C(=O)CC[C@@H]23)[C...,CHEMBL1200374,50.1
2962,O=C(Nc1ccc2[nH]ncc2c1)[C@]12ON=C(c3cccnc3)[C@H...,CHEMBL5184829,10000.0
2963,CCOC(=O)Cc1csc(N/N=C/c2ccc3cc(OC)ccc3c2)n1,CHEMBL5176279,31.0
2964,COc1ccc2cc(/C=N/NC3=NC(=O)CS3)ccc2c1,CHEMBL5177928,42.0
2965,N#Cc1ccc(C(c2ccc(C#N)cc2)n2cncn2)cc1,CHEMBL1444,26.0

In [8]:
handled_canonical_smiles = handled_standard_value[handled_standard_value['canonical_smiles'].notna()]
handled_canonical_smiles

,canonical_smiles,molecule_chembl_id,standard_value
0,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12,CHEMBL341591,7100.0
1,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,CHEMBL2111947,50000.0
2,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21,CHEMBL431859,238.0
3,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21,CHEMBL113637,57.0
4,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21,CHEMBL112021,54.0
...,...,...,...
2961,C=C1C[C@@H]2[C@H](CC[C@]3(C)C(=O)CC[C@@H]23)[C...,CHEMBL1200374,50.1
2962,O=C(Nc1ccc2[nH]ncc2c1)[C@]12ON=C(c3cccnc3)[C@H...,CHEMBL5184829,10000.0
2963,CCOC(=O)Cc1csc(N/N=C/c2ccc3cc(OC)ccc3c2)n1,CHEMBL5176279,31.0
2964,COc1ccc2cc(/C=N/NC3=NC(=O)CS3)ccc2c1,CHEMBL5177928,42.0
2965,N#Cc1ccc(C(c2ccc(C#N)cc2)n2cncn2)cc1,CHEMBL1444,26.0

## Check for Duplicate Values

In [9]:
len(handled_canonical_smiles['molecule_chembl_id'].unique())
len(handled_canonical_smiles['canonical_smiles'].unique())

2116

Duplicates values are there, drop duplicates values

In [10]:
data_nr = handled_canonical_smiles.drop_duplicates(['canonical_smiles'])
data_nr

,canonical_smiles,molecule_chembl_id,standard_value
0,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12,CHEMBL341591,7100.00
1,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,CHEMBL2111947,50000.00
2,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21,CHEMBL431859,238.00
3,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21,CHEMBL113637,57.00
4,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21,CHEMBL112021,54.00
...,...,...,...
2955,CC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1,CHEMBL5203413,0.09
2956,CCC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1,CHEMBL5179009,0.72
2962,O=C(Nc1ccc2[nH]ncc2c1)[C@]12ON=C(c3cccnc3)[C@H...,CHEMBL5184829,10000.00
2963,CCOC(=O)Cc1csc(N/N=C/c2ccc3cc(OC)ccc3c2)n1,CHEMBL5176279,31.00
2964,COc1ccc2cc(/C=N/NC3=NC(=O)CS3)ccc2c1,CHEMBL5177928,42.00

In [11]:
len(data_nr['molecule_chembl_id'].unique())

2116

In [12]:
smiles = []
for smile in data_nr['canonical_smiles'].tolist():
    cpd = str(smile).split('.')
    cpd_max = max(cpd, key=len)
    smiles.append(cpd_max)
data_nr['clean_smiles'] = smiles
data_nr

/var/folders/l3/t2q9429s2kv4n69b2l124_f00000gn/T/ipykernel_15600/3917166689.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nr['clean_smiles'] = smiles

,canonical_smiles,molecule_chembl_id,standard_value,clean_smiles
0,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12,CHEMBL341591,7100.00,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12
1,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,CHEMBL2111947,50000.00,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...
2,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21,CHEMBL431859,238.00,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21
3,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21,CHEMBL113637,57.00,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21
4,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21,CHEMBL112021,54.00,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21
...,...,...,...,...
2955,CC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1,CHEMBL5203413,0.09,CC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1
2956,CCC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1,CHEMBL5179009,0.72,CCC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1
2962,O=C(Nc1ccc2[nH]ncc2c1)[C@]12ON=C(c3cccnc3)[C@H...,CHEMBL5184829,10000.00,O=C(Nc1ccc2[nH]ncc2c1)[C@]12ON=C(c3cccnc3)[C@H...
2963,CCOC(=O)Cc1csc(N/N=C/c2ccc3cc(OC)ccc3c2)n1,CHEMBL5176279,31.00,CCOC(=O)Cc1csc(N/N=C/c2ccc3cc(OC)ccc3c2)n1
2964,COc1ccc2cc(/C=N/NC3=NC(=O)CS3)ccc2c1,CHEMBL5177928,42.00,COc1ccc2cc(/C=N/NC3=NC(=O)CS3)ccc2c1

In [13]:
data_nr.isna().value_counts()

canonical_smiles  molecule_chembl_id  standard_value  clean_smiles
False             False               False           False           2116
dtype: int64

In [14]:
data_nr = data_nr.drop(columns=['canonical_smiles'])
data_nr

,molecule_chembl_id,standard_value,clean_smiles
0,CHEMBL341591,7100.00,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12
1,CHEMBL2111947,50000.00,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...
2,CHEMBL431859,238.00,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21
3,CHEMBL113637,57.00,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21
4,CHEMBL112021,54.00,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21
...,...,...,...
2955,CHEMBL5203413,0.09,CC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1
2956,CHEMBL5179009,0.72,CCC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1
2962,CHEMBL5184829,10000.00,O=C(Nc1ccc2[nH]ncc2c1)[C@]12ON=C(c3cccnc3)[C@H...
2963,CHEMBL5176279,31.00,CCOC(=O)Cc1csc(N/N=C/c2ccc3cc(OC)ccc3c2)n1
2964,CHEMBL5177928,42.00,COc1ccc2cc(/C=N/NC3=NC(=O)CS3)ccc2c1

In [15]:
data_nr.rename(columns={'clean_smiles': 'canonical_smiles'}, inplace=True)
data_nr

,molecule_chembl_id,standard_value,canonical_smiles
0,CHEMBL341591,7100.00,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12
1,CHEMBL2111947,50000.00,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...
2,CHEMBL431859,238.00,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21
3,CHEMBL113637,57.00,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21
4,CHEMBL112021,54.00,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21
...,...,...,...
2955,CHEMBL5203413,0.09,CC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1
2956,CHEMBL5179009,0.72,CCC#CCOc1ccc2cc(C(c3ccc(C#N)cc3)n3cncn3)oc2c1
2962,CHEMBL5184829,10000.00,O=C(Nc1ccc2[nH]ncc2c1)[C@]12ON=C(c3cccnc3)[C@H...
2963,CHEMBL5176279,31.00,CCOC(=O)Cc1csc(N/N=C/c2ccc3cc(OC)ccc3c2)n1
2964,CHEMBL5177928,42.00,COc1ccc2cc(/C=N/NC3=NC(=O)CS3)ccc2c1

In [16]:
data_nr.to_csv('datasets/non_redundant_preprocessed_dataset.csv', index=False)